"""
Enforces that manifests/_pinned_map.yaml (committed, generated by
tools/build_manifests.py) has an entry for every directory currently on disk
under experiments/ and experiments_cluster/ -- the "hand-checked" coverage
guarantee Phase 3 promises for the ~63 pre-existing experiment directories.

If this fails, either a new directory was added to the corpus without
regenerating the pinned map (run `python tools/build_manifests.py`), or an
old one was removed and the map has a stale entry (also fixed by
regenerating).
"""

from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).parent.parent
PINNED_MAP_PATH = REPO_ROOT / "manifests" / "_pinned_map.yaml"


@pytest.mark.needs_artifacts
def test_pinned_map_covers_all_paper_dirs():
    if not PINNED_MAP_PATH.exists():
        pytest.skip("manifests/_pinned_map.yaml not built yet -- run tools/build_manifests.py")

    doc = yaml.safe_load(PINNED_MAP_PATH.read_text(encoding="utf-8")) or {}

    on_disk = set()
    for root_name in ("experiments", "experiments_cluster"):
        root = REPO_ROOT / root_name
        if not root.is_dir():
            continue
        for exp_dir in root.iterdir():
            if exp_dir.is_dir():
                on_disk.add(f"{root_name}/{exp_dir.name}")

    if not on_disk:
        pytest.skip("no experiments/ or experiments_cluster/ artifact corpus found on disk")

    missing = on_disk - set(doc.keys())
    stale = set(doc.keys()) - on_disk
    assert not missing, f"{len(missing)} on-disk directories missing from pinned map: {sorted(missing)[:5]}..."
    assert not stale, f"{len(stale)} pinned-map entries no longer exist on disk: {sorted(stale)[:5]}..."

    for key, entry in doc.items():
        assert entry["kind"] in ("pred", "bandit", "mixed"), f"{key}: unresolved kind {entry['kind']!r}"
