"""
Phase 3: builds content-derived manifests for every directory under
experiments/ and experiments_cluster/, writes them to the sidecar
`manifests/` tree (see mabss/experiments/manifest.py's docstring for why
that's outside both roots), and derives `manifests/_pinned_map.yaml` -- a
committed, human-checkable summary (root, dir name, kind, schema fields
found, content-derived facts, and any name/content mismatches) covering
every one of the 63 pre-existing experiment directories.

Read-only with respect to experiments/ and experiments_cluster/: verified by
`tests/test_golden_artifact_inventory.py`, which re-hashes both trees and
asserts no change.

Usage:
    python tools/build_manifests.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT))

from mabss.experiments.manifest import build_all_manifests  # noqa: E402

PINNED_MAP_PATH = REPO_ROOT / "manifests" / "_pinned_map.yaml"

_PINNED_MAP_HEADER = (
    "# Phase 3 pinned map: one entry per pre-existing experiment directory,\n"
    "# generated by tools/build_manifests.py from CONTENT (not from the\n"
    "# directory name) -- see mabss/experiments/manifest.py. Covers every\n"
    "# directory under experiments/ and experiments_cluster/; enforced by\n"
    "# tests/test_pinned_map_covers_all_paper_dirs.py.\n\n"
)


def _write_pinned_map(manifests: dict[str, dict]) -> None:
    doc = {}
    for key in sorted(manifests):
        m = manifests[key]
        entry = {
            "root": m["root"],
            "dir_name": m["dir_name"],
            "kind": m["kind"],
            "ticker": m["name_fields"].get("TICKER"),
            "policy": m["name_fields"].get("POLICY"),
            "n_arms_actual": m["content_facts"].get("n_arms_actual"),
        }
        if m["mismatches"]:
            entry["mismatches"] = m["mismatches"]
        doc[key] = entry

    PINNED_MAP_PATH.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(doc, sort_keys=True, default_flow_style=False, allow_unicode=True)
    PINNED_MAP_PATH.write_text(_PINNED_MAP_HEADER + body, encoding="utf-8")


def main() -> int:
    print(f"Scanning experiments/, experiments_cluster/ under {REPO_ROOT} ...", file=sys.stderr)
    manifests = build_all_manifests(REPO_ROOT)
    print(f"Built {len(manifests)} manifests.", file=sys.stderr)

    n_mismatch = sum(1 for m in manifests.values() if m["mismatches"])
    print(f"{n_mismatch} directories have name/content mismatches.", file=sys.stderr)
    for key, m in sorted(manifests.items()):
        for mm in m["mismatches"]:
            print(f"  MISMATCH {key}: {mm}", file=sys.stderr)

    _write_pinned_map(manifests)
    print(f"Wrote {PINNED_MAP_PATH}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
